first commit
culto90/java-explore-with-me pull request #1
Opened 2022-10-27 20:04 UTC by culto90

2022-10-30 09:50 UTC, sergeymamonov requested changes

2022-10-30 09:50 UTC, sergeymamonov commented on ewm-stats-application/src/main/java/by/practicum/stats/repositories/HitsAlternativeDao.java
> +        List<ViewStats> viewStats = jdbcTemplate.query(SELECT_UNIQUE_STATS_BY_ALL_PARAMS,
Можно сразу возвращать результат выражения, без создания дополнительной переменной. В методах ниже аналогично.

2022-10-30 09:50 UTC, sergeymamonov commented on ewm-stats-application/src/main/java/by/practicum/stats/services/StatsService.java
> +        if (params.getUris() != null && params.getUnique() == true) {
params.getUnique() == true можно без сравнения с true, а просто params.getUnique() - это выражение уже даст true или false. Ниже аналогично.

2022-10-30 09:50 UTC, sergeymamonov commented on ewm-stats-client/src/main/java/by/practicum/ewm/client/BaseClient.java
> +        generatedPath.append(path + "?");
Смесь конкатенации строк и стрингбилдера. Если уже используете стрингбилдер, то все делайте через него, без конкатенации.

2022-10-30 09:50 UTC, sergeymamonov commented on ewm-stats-client/src/main/java/by/practicum/ewm/client/EwmHitClient.java
> +        List<ViewStatsDto> dtos = rs.getBody();
Можно сразу возвращать результат выполнения, без дополнительной переменной.

2022-10-31 15:51 UTC, culto90 commented on ewm-application/src/main/java/by/practicum/admin/services/AdminEventService.java
> +        if (!(event.getState() == EventState.PENDING)) {
исправил

2022-10-31 15:52 UTC, culto90 commented on ewm-application/src/main/java/by/practicum/admin/services/AdminUserService.java
> +    private final ValidationManager validationManager;
исправил

2022-10-31 15:55 UTC, culto90 commented on ewm-application/src/main/java/by/practicum/authorized/services/AuthorizedEventService.java
> +        User initiator = userRepository.findById(initiatorId)
исправил

2022-10-31 15:57 UTC, culto90 commented on ewm-application/src/main/java/by/practicum/authorized/services/AuthorizedRequestService.java
> +        User user = userRepository.findById(userId)
исправил

2022-10-31 15:58 UTC, culto90 commented on ewm-application/src/main/java/by/practicum/common/services/CommonEventService.java
> +                if (event.getParticipantLimit() >= confirmedRequests) {
исправил

2022-10-31 16:01 UTC, culto90 commented on ewm-stats-application/src/main/java/by/practicum/stats/repositories/HitsAlternativeDao.java
> +        List<ViewStats> viewStats = jdbcTemplate.query(SELECT_UNIQUE_STATS_BY_ALL_PARAMS,
исправил

2022-10-31 16:02 UTC, culto90 commented on ewm-stats-application/src/main/java/by/practicum/stats/services/StatsService.java
> +        if (params.getUris() != null && params.getUnique() == true) {
исправил

2022-10-31 16:05 UTC, culto90 commented on ewm-stats-client/src/main/java/by/practicum/ewm/client/BaseClient.java
> +        generatedPath.append(path + "?");
исправид

2022-10-31 16:12 UTC, culto90 commented on ewm-application/src/main/java/by/practicum/utils/validations/ValidationManager.java
> +    private final List<ValidationRule> rules = new ArrayList<>();
убрал вообще его

2022-11-01 19:42 UTC, sergeymamonov approved these changes

2022-11-02 16:50 UTC, merged